apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: {{ .Values.ProcessorManagedIdentity.name}}
  namespace: {{ .Values.ProcessorManagedIdentity.namespace }}
spec:
  type: 0 # 0 means User-assigned MSI
  resourceID: {{ .Values.ProcessorManagedIdentity.resourceID}}
  clientID:  {{ .Values.ProcessorManagedIdentity.clientID}}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: sb-processor-identity-binding
  namespace: {{ .Values.ProcessorManagedIdentity.namespace }}
spec:
  azureIdentity: {{ .Values.ProcessorManagedIdentity.name}}
  selector: order-processor